# Generated by Django 4.2.7 on 2023-11-23 23:00

import ckeditor.fields
from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
            ],
            options={
                'verbose_name_plural': 'Про нас',
                'ordering': ('title',),
            },
        ),
    ]
