# Generated by Django 4.2.7 on 2023-11-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('servise_1', models.CharField(max_length=255, verbose_name='Сервіс 1 Заголовок')),
                ('serv_1_desc', models.TextField(max_length=500, verbose_name='Сервіс 1 Опис')),
                ('servise_2', models.CharField(max_length=255, verbose_name='Сервіс 2 Заголовок')),
                ('serv_2_desc', models.TextField(max_length=500, verbose_name='Сервіс 2 Опис')),
                ('servise_3', models.CharField(max_length=255, verbose_name='Сервіс 3 Заголовок')),
                ('serv_3_desc', models.TextField(max_length=500, verbose_name='Сервіс 3 Опис')),
                ('servise_4', models.CharField(max_length=255, verbose_name='Сервіс 4 Заголовок')),
                ('serv_4_desc', models.TextField(max_length=500, verbose_name='Сервіс 4 Опис')),
            ],
            options={
                'verbose_name_plural': 'Наші сервіси',
                'ordering': ('title',),
            },
        ),
    ]
