# Generated by Django 4.2.7 on 2023-11-26 01:37

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Модель авто')),
                ('manufacturer', models.CharField(max_length=75, verbose_name='Виробник')),
                ('data', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дата випуску')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пробіг')),
                ('transmission', models.CharField(blank=True, choices=[('M', 'Manual'), ('A', 'Automatic')], default='A', max_length=1, verbose_name='Коробка передач')),
                ('seats', models.CharField(blank=True, choices=[('5', '5 Adults'), ('4', '4 Adults'), ('3', '3 Adults'), ('2', '2 Adults')], default='5', max_length=1, verbose_name='Кількість місць')),
                ('luggage', models.CharField(blank=True, choices=[('5', '5 Bags'), ('4', '4 Bags'), ('3', '3 Bags'), ('2', '2 Bags')], default='4', max_length=1, verbose_name='Кількість багажних місць')),
                ('fuel', models.CharField(blank=True, choices=[('D', 'Diesel'), ('G', 'Gas'), ('H', 'Hybrid'), ('E', 'Electric')], default='G', max_length=1, verbose_name='Паливо')),
            ],
            options={
                'verbose_name_plural': 'Автомобілі',
                'ordering': ('title',),
            },
        ),
    ]
