# Generated by Django 4.2.7 on 2023-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='desc',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Опис'),
        ),
    ]
