# Generated by Django 4.2.7 on 2023-11-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_car_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='data',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Дата випуску'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Пробіг'),
        ),
    ]
