# Generated by Django 4.2.7 on 2023-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_car_data_alter_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='airconditions',
            field=models.BooleanField(default=False, verbose_name='Airconditions'),
        ),
        migrations.AddField(
            model_name='car',
            name='audio',
            field=models.BooleanField(default=False, verbose_name='Audio input'),
        ),
        migrations.AddField(
            model_name='car',
            name='bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_kit',
            field=models.BooleanField(default=False, verbose_name='Car Kit'),
        ),
        migrations.AddField(
            model_name='car',
            name='child',
            field=models.BooleanField(default=False, verbose_name='Child Seat'),
        ),
        migrations.AddField(
            model_name='car',
            name='climate_control',
            field=models.BooleanField(default=False, verbose_name='Climate control'),
        ),
        migrations.AddField(
            model_name='car',
            name='gps',
            field=models.BooleanField(default=False, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='car',
            name='long_term_trips',
            field=models.BooleanField(default=False, verbose_name='Long Term Trips'),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage_f',
            field=models.BooleanField(default=False, verbose_name='Luggage'),
        ),
        migrations.AddField(
            model_name='car',
            name='music',
            field=models.BooleanField(default=False, verbose_name='Music'),
        ),
        migrations.AddField(
            model_name='car',
            name='onboard_computer',
            field=models.BooleanField(default=False, verbose_name='Onboard computer'),
        ),
        migrations.AddField(
            model_name='car',
            name='remote_central_locking',
            field=models.BooleanField(default=False, verbose_name='Remote central locking'),
        ),
        migrations.AddField(
            model_name='car',
            name='seat_belt',
            field=models.BooleanField(default=False, verbose_name='Seat Belt'),
        ),
        migrations.AddField(
            model_name='car',
            name='sleeping_bed',
            field=models.BooleanField(default=False, verbose_name='Sleeping Bed'),
        ),
        migrations.AddField(
            model_name='car',
            name='water',
            field=models.BooleanField(default=False, verbose_name='Water'),
        ),
    ]
