# Generated by Django 4.2.7 on 2023-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, verbose_name='Адреса')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта ')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'ordering': ('address',),
            },
        ),
    ]
