# Generated by Django 4.2.7 on 2023-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='fb_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на youtube'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='inst_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='twi_url',
            field=models.URLField(blank=True, default='https://www.x.com/', verbose_name='Посилання на facebook'),
        ),
    ]
