# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_contacts_fb_url_contacts_inst_url_contacts_twi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_hour',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Ціна Година'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=995, max_digits=10, verbose_name='Ціна Місяць'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна День'),
        ),
    ]
