# Generated by Django 4.2.7 on 2024-01-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_car_price_hour_car_price_month_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.car')),
            ],
            options={
                'verbose_name_plural': 'Бронь',
                'ordering': ('-pick_up_date',),
            },
        ),
    ]
