# Generated by Django 4.2.7 on 2024-01-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_alter_booking_pick_up_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pick_up_time',
        ),
    ]
